### ISSUE TITLE
[REQ] Copy-Paste buttons in UI

### ISSUE THREAD

**Issue by rpodcast** [unix-streamdeck/streamdeckui#18]
Having the ability to copy a particular button in the UI and directly paste it to an empty button slot would be a big time-saver for me. Often I want to have near the same functionality for buttons in different pages, but with only slight differences.

**Comment by The-Jonsey** [comment]
Yeah that's definitely happening, don't know why I never thought of it to be honest

**Comment by ymauray** [comment]
Do you need help with that? I can have a look.

**Comment by The-Jonsey** [comment]
Added in #19
