### ISSUE TITLE
Make the file dialogue box resizeable

### ISSUE THREAD

**Issue by ScuttleSE** [unix-streamdeck/streamdeckui#3]
Right now it shows just 8 icons, which makes it pretty difficult to navigate the filesystem

**Comment by ScuttleSE** [comment]
In addition, the file dialogue box jumps back to $HOME instead of remembering the last folder it was in previously.

**Comment by The-Jonsey** [comment]
Yeah this is a known issue to do with the UI toolkit that is being used, I'm planning on looking into different making the open file dialogue use the system's default open file i.e naut, dolphin, thunar etc.

**Comment by andydotxyz** [comment]
For the second point you could use SetLocation to be the place the last item was opened from
