### ISSUE TITLE
Saving inconsistent

### ISSUE THREAD

**Issue by ScuttleSE** [unix-streamdeck/streamdeckui#4]
* Enter text in one of the boxes
* Click save
* Filedate on the config file updates, but nothing is updated in it
* Click Preview, then click Save
* Config file is updated with the new config

**Comment by The-Jonsey** [comment]
Yeah that's a good point, it was part of the intended flow that preview pushes to device, then save commits the config running on the device to disk, but I can see how that could be confusing, and it might be worth looking into making the save button also push the config to the device first
